import type { Metadata } from "next";
import { Playfair_Display } from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/hooks/useTheme";

const inter = Playfair_Display({ subsets: ["latin"],
weight: ['400', '500', '600', '700', '800', '900'],
style: ["normal", "italic"],
});

export const metadata: Metadata = {
  title: "Age Me",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ThemeProvider>
      <html lang="en" className="dark">
        <body className={inter.className}>
          {children}
        </body>
      </html>
    </ThemeProvider>
  );
}
